POST http://localhost:3000/signin
Content-Type: application/json

{
    "username":"Hemanth",
    "password":"Hemanth"
}
###
GET http://localhost:3000/user
Content-Type: application/json
###
POST http://localhost:3000/logout
Content-Type: application/json

